   [build]
     publish = "app/dist"  # Adjust this path if your build output is in a different location
     command = "cd app && bun run build"  # Change to the app directory before running the build

   [[redirects]]
     from = "/*"
     to = "/index.html"
     status = 200
     force = true